name: openid4vc-high-assurance-interoperability-profile document push
on:
  push:
    paths:
      - 'openid4vc*.md'

jobs:
    compile-openid4vc-high-assurance-interoperability-profile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run the build process with Docker
            run: |  
                ls
                docker run \
                -v /${{ github.workspace }}:/data danielfett/markdown2rfc \
                openid4vc-high-assurance-interoperability-profile-1_0.md
          - name: rename
            run: |
                mv ./openid4vc-high-assurance-interoperability-profile*.html ./openid4vc-high-assurance-interoperability-profile-wg-draft.html
          - uses: actions/upload-artifact@v4
            with:
                # Artifact name
                name: output # optional
                # Destination path
                path: ./openid4vc-high-assurance-interoperability-profile*.html # optional
    
    publish-to-pages:
      name: Publish to GitHub Pages
      if: github.ref == 'refs/heads/main'
      needs: compile-openid4vc-high-assurance-interoperability-profile
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: output
        - name: Upload pages artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: .
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
